version: "3.7"
services:
    app:
        image: bamboo:${application_tag}
        build:
            context: application
            args:
                PythonVersion: ${python_version}
        environment:
            ENV: ${execution_env}
        volumes:
            - "./application/:${container_mountpoint_application}"
            - "./test/:/var/test"
        stdin_open: true
        tty: true
