version: "3.7"
services:
    app:
        image: bamboo:${application_tag}
        build:
            context: application
            args:
                PythonVersion: ${python_version}
        volumes:
            - "./application/:${container_mountpoint_application}"
            - "./test/:/var/test"
        environment:
            REJECT_FOLDER_PATH: './reject/'
            IPv4_FOLDER_PATH: './ipv4/'
            REJECT_FILE_NAME: 'reject_by_country.gcsh'
        stdin_open: true
        tty: true
        command: python app.py

